### Get all albums (v1)
GET http://localhost:3000/api/v1.0/albums HTTP/1.1

###

### Get all albums (v2)
GET http://localhost:3000/api/v2.0/albums HTTP/1.1

###

### Get a specific album by ID (v1)
GET http://localhost:3000/api/v1.0/albums/3 HTTP/1.1

###

### Get a specific album by ID (v2)
GET http://localhost:3000/api/v2.0/albums/3 HTTP/1.1

###

### Add a new album (v1)
POST http://localhost:3000/api/v1.0/albums HTTP/1.1
Content-Type: application/json

{
  "title": "Alessia Columban",
  "description": "Gf of the year"
}

###

### Add a new album (v2)
POST http://localhost:3000/api/v2.0/albums HTTP/1.1
Content-Type: application/json

{
  "title": "AI Creations"
}

###

### Update an existing album (v1)
PUT http://localhost:3000/api/v1.0/albums/25 HTTP/1.1
Content-Type: application/json

{
  "title": "AI Creations",
  "description": "AI images created with AI tools"
}

###

### Update an existing album (v2)
PUT http://localhost:3000/api/v2.0/albums/25 HTTP/1.1
Content-Type: application/json

{
  "title": "AI Creations",
  "description": "AI images created with AI tools"
}

###

### Delete an album by ID (v1)
DELETE http://localhost:3000/api/v1.0/albums/30 HTTP/1.1

###

### Delete an album by ID (v2)
DELETE http://localhost:3000/api/v2.0/albums/24 HTTP/1.1

###

### Get all photos
GET http://localhost:3000/api/photos HTTP/1.1

###

### Get a specific photo by ID
GET http://localhost:3000/api/photos/6 HTTP/1.1

###

### Add a new photo
POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: application/json

{
  "albumId": 22,
  "titled": "Smoking Roses",
  "description": "Pinterst image",
  "url": "https://i.pinimg.com/originals/d5/6d/7d/d56d7d9b840774e9a05c11ffab5330e0.jpg"
}

### Add a new photo
POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: application/json

{
  "albumId": 1,
  "title": "AI Art Creation",
  "description": "A photo of AI art creation.",
  "url": "https://www.elegantthemes.com/blog/wp-content/uploads/2023/06/What-is-AI-1.jpg"
}

### Add a new photo
POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: application/json

{
  "albumId": 2,
  "title": "Landscape",
  "description": "A beautiful landscape.",
  "url": "https://images.pexels.com/photos/1421903/pexels-photo-1421903.jpeg?cs=srgb&dl=pexels-eberhardgross-1421903.jpg&fm=jpg"
}

### Add a new photo
POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: application/json

{
  "albumId": 2,
  "title": "Nature",
  "description": "Nature picture 1920x1080",
  "url": "https://images.pexels.com/photos/640781/pexels-photo-640781.jpeg?cs=srgb&dl=pexels-eberhardgross-640781.jpg&fm=jpg"
}

### Add a new photo
POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: application/json

{
  "albumId": 2,
  "title": "Icy plains",
  "description": "An icy plains picture",
  "url": "https://wallpapers.com/images/hd/4k-nature-in-ice-wvdjbvbvxn12plp6.jpg"
}

### Update an existing photo
PUT http://localhost:3000/api/photos/10 HTTP/1.1
Content-Type: application/json

{
  "albumId": 1,
  "title": "AI Art Creation",
  "description": "Weird Picture",
  "url": "https://i.pinimg.com/736x/3f/68/48/3f6848fde91b1a9110b5cc36fe6b4d09.jpg"
}

### Delete a photo by ID
https://i.pinimg.com/736x/3f/68/48/3f6848fde91b1a9110b5cc36fe6b4d09.jpg
https://www.elegantthemes.com/blog/wp-content/uploads/2023/06/What-is-AI-1.jpg