### Get all albums
GET http://localhost:3000/api/albums HTTP/1.1

###

### Get a specific album by ID
GET http://localhost:3000/api/albums/1 HTTP/1.1

###

### Add a new album
POST http://localhost:3000/api/albums HTTP/1.1
Content-Type: application/json

{
  "title": "AI Creations",
  "description": "Wtf"
}

###

### Update an existing album
PUT http://localhost:3000/api/albums/3 HTTP/1.1
Content-Type: application/json

{
  "title": "AI Creations",
  "description": "AI images created with AI tools"
}

###

### Delete an album by ID
DELETE http://localhost:3000/api/albums/5 HTTP/1.1

###

### Get all photos
GET http://localhost:3000/api/photos HTTP/1.1

###

### Get a specific photo by ID
GET http://localhost:3000/api/photos/1 HTTP/1.1

###

### Add a new photo
POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: application/json

{
  "title": "AI Image",
  "description": "AI image created with AI tools",
  "url": "https://www.google.com"
}
